[project]
name = "urza"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "cmd2>=3.1.2",
    "fastapi>=0.128.0",
    "pydantic>=2.12.5",
    "telethon>=1.42.0",
    "uvicorn>=0.40.0",
]
